apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-disconnected-policy-repomirror
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: role-policy-musthave
        spec:
          remediationAction: enforce
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1alpha1
                kind: ImageContentSourcePolicy
                metadata:
                  name: ubi8repo
                spec:
                  repositoryDigestMirrors:
                  - mirrors:
                    - example.io/example/ubi-minimal
                    source: registry.access.redhat.com/ubi8/ubi-minimal
                  - mirrors:
                    - example.com/example/ubi-minimal
                    source: registry.access.redhat.com/ubi8/ubi-minimal
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-disconnected-binding-repomirror
  namespace: default
placementRef:
  name: openshift-disconnected-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: openshift-disconnected-policy-repomirror
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-disconnected-placement-rule
  namespace: default
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      vendor: OpenShift
